INSERT INTO node (node_id, node_name, node_type, status, authority_srid, display_srid, geometry_2d, z_top, z_bottom, bury_depth, elevation_ref, created_at, updated_at) VALUES
('NODE-001', '北区入口节点', 'inlet', 'ACTIVE', 'EPSG:4490', 'EPSG:3857', 'POINT(120.1533 30.2741)', 2.50, -1.20, 3.70, 'MSL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NODE-002', '主干分流节点', 'junction', 'ACTIVE', 'EPSG:4490', 'EPSG:3857', 'POINT(120.1634 30.2842)', 2.30, -1.40, 3.70, 'MSL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NODE-003', '东区泵站节点', 'pump_station', 'ACTIVE', 'EPSG:4490', 'EPSG:3857', 'POINT(120.1735 30.2943)', 2.10, -1.70, 3.80, 'MSL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO segment (segment_id, segment_name, start_node_id, end_node_id, segment_type, length_meter, status, created_at, updated_at) VALUES
('SEG-001', '北区主干一段', 'NODE-001', 'NODE-002', 'trunk', 520.40, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SEG-002', '东区分支一段', 'NODE-002', 'NODE-003', 'branch', 310.80, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO facility (facility_id, facility_name, segment_id, node_id, facility_type, position_meter, status, created_at, updated_at) VALUES
('FAC-001', '阀门井-01', 'SEG-001', 'NODE-001', 'valve_well', 80.00, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('FAC-002', '检测井-02', 'SEG-001', 'NODE-002', 'inspection_well', 250.00, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('FAC-003', '阀门井-03', 'SEG-002', 'NODE-003', 'valve_well', 120.00, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO device (device_id, device_name, facility_id, segment_id, node_id, protocol_type, last_heartbeat, status, created_at, updated_at) VALUES
('DEV-001', '压力传感器-01', 'FAC-001', 'SEG-001', 'NODE-001', 'MQTT', CURRENT_TIMESTAMP, 'ONLINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DEV-002', '流量计-02', 'FAC-002', 'SEG-001', 'NODE-002', 'MODBUS', CURRENT_TIMESTAMP, 'ONLINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DEV-003', '振动传感器-03', 'FAC-003', 'SEG-002', 'NODE-003', 'MQTT', CURRENT_TIMESTAMP, 'ONLINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO incident (incident_id, segment_id, node_id, title, severity, status, created_at, updated_at) VALUES
('INC-001', 'SEG-001', 'NODE-002', '压力异常升高', 'HIGH', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('INC-002', 'SEG-002', 'NODE-003', '流量下降预警', 'MEDIUM', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO work_order (work_order_id, incident_id, segment_id, node_id, assignee, status, created_at, updated_at) VALUES
('WO-001', 'INC-001', 'SEG-001', 'NODE-002', 'zhangsan', 'DISPATCHED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('WO-002', 'INC-002', 'SEG-002', 'NODE-003', 'lisi', 'CREATED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO model_result (model_result_id, segment_id, node_id, model_code, model_version, status, created_at, updated_at) VALUES
('MR-001', 'SEG-001', 'NODE-002', 'LEAK-RISK', 'v1.0.0', 'VALID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MR-002', 'SEG-002', 'NODE-003', 'PRESSURE-ANOMALY', 'v1.0.0', 'VALID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_account (
    user_id, username, display_name, primary_region_id, status, token_valid_after, disabled_at, created_at, updated_at
) VALUES
('U-ADMIN-001', 'admin', '平台管理员', 'GLOBAL', 'ACTIVE', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('U-DISPATCH-001', 'hz_dispatcher', '杭州区域调度员', 'REGION-HZ', 'ACTIVE', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('U-INSPECT-001', 'zhangsan', '巡检人员张三', 'REGION-HZ', 'ACTIVE', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('U-ALGO-001', 'algo_user', '算法工程师', 'REGION-HZ', 'ACTIVE', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('U-LEADER-001', 'leader_readonly', '领导只读', 'CITY-HZ', 'ACTIVE', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('U-OIDC-001', 'oidc_static_sample', '静态权限样例用户', 'REGION-HZ', 'ACTIVE', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('U-B04-DISABLED-001', 'disabled_demo', 'B04禁用用户样例', 'REGION-HZ', 'DISABLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('U-B04-CONVERGED-001', 'converged_demo', 'B04权限收敛样例', 'REGION-HZ', 'ACTIVE', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('U-B05-COMMAND-001', 'emergency_command', 'B05应急指挥样例', 'REGION-EMGC-HZ', 'ACTIVE', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('U-B06-BLOCKED-001', 'gateway_blocked_user', 'B06网关阻断样例', 'REGION-HZ', 'ACTIVE', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO rbac_role (role_code, role_name, description, read_only) VALUES
('PLATFORM_ADMIN', '平台管理员', '全平台管理权限', FALSE),
('REGIONAL_DISPATCHER', '区域调度员', '仅限辖区调度与订阅', FALSE),
('INSPECTOR', '巡检人员', '仅可查看和处理本人任务', FALSE),
('ALGORITHM_ENGINEER', '算法工程师', '默认仅可访问脱敏特征视图', FALSE),
('LEADER_READONLY', '领导只读', '只读查看聚合态势与报表', TRUE),
('BREAK_GLASS_COMMAND', '应急旁路指挥', '仅应急指挥必需能力', FALSE);

INSERT INTO rbac_permission (permission_code, permission_type, resource_code, description) VALUES
('ENTRY:PORTAL', 'ENTRY', 'PORTAL', '门户入口'),
('ENTRY:MGMT', 'ENTRY', 'MGMT', '综合管理平台入口'),
('ENTRY:EMGC', 'ENTRY', 'EMGC', '应急指挥平台入口'),
('ENTRY:DIAG', 'ENTRY', 'DIAG', '智能诊断中枢入口'),
('ENTRY:SUPPORT', 'ENTRY', 'SUPPORT', '平台支撑层入口'),
('MENU:ASSET:READ', 'MENU', 'ASSET', '资产查看'),
('MENU:ASSET:WRITE', 'MENU', 'ASSET', '资产编辑'),
('MENU:WORKORDER:READ', 'MENU', 'WORKORDER', '工单查看'),
('MENU:WORKORDER:DISPATCH', 'MENU', 'WORKORDER', '工单派发'),
('MENU:MODEL:READ', 'MENU', 'MODEL', '模型查看'),
('MENU:MODEL:WRITE', 'MENU', 'MODEL', '模型发布与回退'),
('MENU:DASHBOARD:READ', 'MENU', 'DASHBOARD', '态势看板只读');

INSERT INTO rbac_role_permission (role_code, permission_code) VALUES
('PLATFORM_ADMIN', 'ENTRY:PORTAL'),
('PLATFORM_ADMIN', 'ENTRY:MGMT'),
('PLATFORM_ADMIN', 'ENTRY:EMGC'),
('PLATFORM_ADMIN', 'ENTRY:DIAG'),
('PLATFORM_ADMIN', 'ENTRY:SUPPORT'),
('PLATFORM_ADMIN', 'MENU:ASSET:READ'),
('PLATFORM_ADMIN', 'MENU:ASSET:WRITE'),
('PLATFORM_ADMIN', 'MENU:WORKORDER:READ'),
('PLATFORM_ADMIN', 'MENU:WORKORDER:DISPATCH'),
('PLATFORM_ADMIN', 'MENU:MODEL:READ'),
('PLATFORM_ADMIN', 'MENU:MODEL:WRITE'),
('PLATFORM_ADMIN', 'MENU:DASHBOARD:READ'),
('REGIONAL_DISPATCHER', 'ENTRY:MGMT'),
('REGIONAL_DISPATCHER', 'ENTRY:EMGC'),
('REGIONAL_DISPATCHER', 'MENU:ASSET:READ'),
('REGIONAL_DISPATCHER', 'MENU:WORKORDER:READ'),
('REGIONAL_DISPATCHER', 'MENU:WORKORDER:DISPATCH'),
('INSPECTOR', 'ENTRY:EMGC'),
('INSPECTOR', 'MENU:WORKORDER:READ'),
('ALGORITHM_ENGINEER', 'ENTRY:DIAG'),
('ALGORITHM_ENGINEER', 'MENU:MODEL:READ'),
('LEADER_READONLY', 'ENTRY:EMGC'),
('LEADER_READONLY', 'MENU:DASHBOARD:READ'),
('LEADER_READONLY', 'MENU:WORKORDER:READ'),
('BREAK_GLASS_COMMAND', 'ENTRY:EMGC'),
('BREAK_GLASS_COMMAND', 'MENU:DASHBOARD:READ'),
('BREAK_GLASS_COMMAND', 'MENU:WORKORDER:READ'),
('BREAK_GLASS_COMMAND', 'MENU:WORKORDER:DISPATCH'),
('BREAK_GLASS_COMMAND', 'MENU:ASSET:READ');

INSERT INTO rbac_user_role (user_id, role_code) VALUES
('U-ADMIN-001', 'PLATFORM_ADMIN'),
('U-DISPATCH-001', 'REGIONAL_DISPATCHER'),
('U-INSPECT-001', 'INSPECTOR'),
('U-ALGO-001', 'ALGORITHM_ENGINEER'),
('U-LEADER-001', 'LEADER_READONLY'),
('U-OIDC-001', 'REGIONAL_DISPATCHER'),
('U-B04-DISABLED-001', 'REGIONAL_DISPATCHER'),
('U-B04-CONVERGED-001', 'REGIONAL_DISPATCHER'),
('U-B05-COMMAND-001', 'BREAK_GLASS_COMMAND'),
('U-B06-BLOCKED-001', 'LEADER_READONLY');

INSERT INTO user_data_scope (user_id, scope_type, scope_value) VALUES
('U-DISPATCH-001', 'REGION', 'REGION-HZ'),
('U-DISPATCH-001', 'REGION', 'REGION-BINJIANG'),
('U-INSPECT-001', 'REGION', 'REGION-HZ'),
('U-INSPECT-001', 'ASSIGNEE', 'zhangsan'),
('U-ALGO-001', 'DATA_VIEW', 'MASKED_FEATURE'),
('U-LEADER-001', 'REGION_AGGREGATE', 'CITY-HZ'),
('U-OIDC-001', 'REGION', 'REGION-HZ'),
('U-B04-DISABLED-001', 'REGION', 'REGION-HZ'),
('U-B04-CONVERGED-001', 'REGION', 'REGION-HZ'),
('U-B05-COMMAND-001', 'REGION', 'REGION-EMGC-HZ'),
('U-B06-BLOCKED-001', 'REGION', 'REGION-HZ');

INSERT INTO topic_scope_rule (role_code, topic_pattern, description) VALUES
('PLATFORM_ADMIN', '#', '全量订阅'),
('REGIONAL_DISPATCHER', 'region.{regionId}.alerts.#', '辖区告警订阅'),
('REGIONAL_DISPATCHER', 'region.{regionId}.workorder.#', '辖区工单订阅'),
('INSPECTOR', 'user.{userId}.workorder.#', '本人工单订阅'),
('ALGORITHM_ENGINEER', 'diag.model.#', '模型特征与结果订阅'),
('LEADER_READONLY', 'city.aggregate.#', '聚合态势只读订阅'),
('BREAK_GLASS_COMMAND', 'region.{regionId}.alerts.#', '应急辖区告警订阅'),
('BREAK_GLASS_COMMAND', 'region.{regionId}.workorder.#', '应急辖区工单订阅');

INSERT INTO emergency_account (
    account_id, username, linked_user_id, password_hash, status, expires_at,
    activated_at, activated_by, revoked_at, revoke_reason, last_login_at, created_at, updated_at
) VALUES
('EA-B05-ACTIVE-001', 'bg_active_hz', 'U-B05-COMMAND-001', '$2a$10$XLroJSsTdLHDMUSWLaRW3.kug5o6bkxCsnsGlFcO.DTOZNlFWqlBe', 'ACTIVE', TIMESTAMP '2099-12-31 23:59:59', CURRENT_TIMESTAMP, 'U-ADMIN-001', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('EA-B05-INACTIVE-001', 'bg_inactive_hz', 'U-B05-COMMAND-001', '$2a$10$NXBxNqirOQiQCtYadX/USeOh0BRZ49mcjzIc3ARQeTANT1Uyuj3ci', 'INACTIVE', TIMESTAMP '2099-12-31 23:59:59', NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('EA-B05-EXPIRED-001', 'bg_expired_hz', 'U-B05-COMMAND-001', '$2a$10$5cEw4Q60dh/pL.jB/.cLYutdp9TFiPkRfn7KduEp0Rcro/zzHXOmK', 'EXPIRED', TIMESTAMP '2024-01-01 00:00:00', CURRENT_TIMESTAMP, 'U-ADMIN-001', CURRENT_TIMESTAMP, 'AUTO_EXPIRED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO auth_session (
    session_id, user_id, auth_mode, emergency_account_id, status, revoked_at, revoke_reason, client_ip, user_agent, created_at, updated_at
) VALUES
('SESSION-ACTIVE-001', 'U-DISPATCH-001', 'STANDARD', NULL, 'ACTIVE', NULL, NULL, '127.0.0.1', 'seed-active-session', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SESSION-ROTATE-001', 'U-OIDC-001', 'STANDARD', NULL, 'ACTIVE', NULL, NULL, '127.0.0.1', 'seed-rotating-session', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SESSION-REVOKED-001', 'U-LEADER-001', 'STANDARD', NULL, 'REVOKED', CURRENT_TIMESTAMP, 'LOGOUT', '127.0.0.1', 'seed-logged-out-session', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SESSION-REPLAY-001', 'U-INSPECT-001', 'STANDARD', NULL, 'REVOKED', CURRENT_TIMESTAMP, 'REPLAY_DETECTED', '127.0.0.1', 'seed-replay-blocked-session', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SESSION-B04-DISABLED-001', 'U-B04-DISABLED-001', 'STANDARD', NULL, 'REVOKED', CURRENT_TIMESTAMP, 'ACCOUNT_DISABLED', '127.0.0.1', 'seed-disabled-session', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SESSION-B04-CONVERGED-001', 'U-B04-CONVERGED-001', 'STANDARD', NULL, 'REVOKED', CURRENT_TIMESTAMP, 'PERMISSION_CHANGED', '127.0.0.1', 'seed-converged-session', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SESSION-B05-ACTIVE-001', 'U-B05-COMMAND-001', 'BREAK_GLASS', 'EA-B05-ACTIVE-001', 'ACTIVE', NULL, NULL, '127.0.0.1', 'seed-break-glass-session', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SESSION-B05-EXPIRED-001', 'U-B05-COMMAND-001', 'BREAK_GLASS', 'EA-B05-EXPIRED-001', 'REVOKED', CURRENT_TIMESTAMP, 'ACCOUNT_EXPIRED', '127.0.0.1', 'seed-break-glass-expired-session', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO auth_refresh_token (
    token_id, user_id, token_hash, session_id, auth_mode, emergency_account_id, issued_at, expires_at,
    rotated_from_token_id, replaced_by_token_id, status, client_ip, user_agent, created_at, updated_at
) VALUES
('RT-ACTIVE-001', 'U-DISPATCH-001', '2201cdb5f5026c5d8d933edd346fce1b55a4639c7e2788d971ca3d33ee512244', 'SESSION-ACTIVE-001', 'STANDARD', NULL, CURRENT_TIMESTAMP, TIMESTAMP '2099-12-31 23:59:59', NULL, NULL, 'ACTIVE', '127.0.0.1', 'seed-active-refresh-token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RT-ROTATED-OLD-001', 'U-OIDC-001', 'b0e5c06acaf04b63daa2b96f41cf9ce3bdbccc2cbe148ba955f02e76fbd1640a', 'SESSION-ROTATE-001', 'STANDARD', NULL, CURRENT_TIMESTAMP, TIMESTAMP '2099-12-31 23:59:59', NULL, 'RT-ROTATED-NEW-001', 'ROTATED', '127.0.0.1', 'seed-rotated-refresh-token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RT-ROTATED-NEW-001', 'U-OIDC-001', '58ebeec618e7aed94b4871b31a1990aa59494e9bfdd90934ab18aa5b0eecc612', 'SESSION-ROTATE-001', 'STANDARD', NULL, CURRENT_TIMESTAMP, TIMESTAMP '2099-12-31 23:59:59', 'RT-ROTATED-OLD-001', NULL, 'ACTIVE', '127.0.0.1', 'seed-rotated-refresh-token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RT-REVOKED-001', 'U-LEADER-001', 'beda9b236175a1a46629c49d11dd29408011bd2a3a239c3e1916e6e8c598eeb6', 'SESSION-REVOKED-001', 'STANDARD', NULL, CURRENT_TIMESTAMP, TIMESTAMP '2099-12-31 23:59:59', NULL, NULL, 'REVOKED', '127.0.0.1', 'seed-revoked-refresh-token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RT-REPLAY-001', 'U-INSPECT-001', '8b96f05c3f907e9ce5dd8315bd97279231be36f9796f6d8655e1e56ee3a3090f', 'SESSION-REPLAY-001', 'STANDARD', NULL, CURRENT_TIMESTAMP, TIMESTAMP '2099-12-31 23:59:59', NULL, NULL, 'REPLAY_BLOCKED', '127.0.0.1', 'seed-replay-refresh-token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RT-B04-DISABLED-001', 'U-B04-DISABLED-001', 'df1938af8037f1de7f832ddfac93e8e6ec6ae42dc95f38ec5d7b0f4b5334c2ce', 'SESSION-B04-DISABLED-001', 'STANDARD', NULL, CURRENT_TIMESTAMP, TIMESTAMP '2099-12-31 23:59:59', NULL, NULL, 'REVOKED', '127.0.0.1', 'seed-disabled-refresh-token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RT-B04-CONVERGED-001', 'U-B04-CONVERGED-001', '4b0437f6ec0bf4d5e3c196f01a80fbcea38c5f7235ea34e9985ef1fd266a6cc4', 'SESSION-B04-CONVERGED-001', 'STANDARD', NULL, CURRENT_TIMESTAMP, TIMESTAMP '2099-12-31 23:59:59', NULL, NULL, 'REVOKED', '127.0.0.1', 'seed-converged-refresh-token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RT-B05-ACTIVE-001', 'U-B05-COMMAND-001', '4f5a7cbf2a1ec9d5082e1769c5b353eaa0be7e4b28d18e1e7d4c819d68c89f33', 'SESSION-B05-ACTIVE-001', 'BREAK_GLASS', 'EA-B05-ACTIVE-001', CURRENT_TIMESTAMP, TIMESTAMP '2099-12-31 23:59:59', NULL, NULL, 'ACTIVE', '127.0.0.1', 'seed-break-glass-refresh-token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RT-B05-EXPIRED-001', 'U-B05-COMMAND-001', 'ee6394c15917f13d8fdf37386057593fe0f4a25a72f3255828e8fdafbfd7e85f', 'SESSION-B05-EXPIRED-001', 'BREAK_GLASS', 'EA-B05-EXPIRED-001', CURRENT_TIMESTAMP, TIMESTAMP '2099-12-31 23:59:59', NULL, NULL, 'REVOKED', '127.0.0.1', 'seed-break-glass-expired-refresh-token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO security_audit (
    event_type, user_id, token_id, session_id, auth_mode, emergency_account_id, outcome, detail, client_ip, user_agent, trace_id, created_at
) VALUES
('TOKEN_REFRESH_SUCCESS', 'U-OIDC-001', 'RT-ROTATED-OLD-001', 'SESSION-ROTATE-001', 'STANDARD', NULL, 'SUCCESS', 'Seed audit for rotated refresh token flow', '127.0.0.1', 'seed-audit-success', 'TRACE-SEED-001', CURRENT_TIMESTAMP),
('TOKEN_REFRESH_REVOKED', 'U-LEADER-001', 'RT-REVOKED-001', 'SESSION-REVOKED-001', 'STANDARD', NULL, 'DENY', 'Seed audit for revoked refresh token reuse', '127.0.0.1', 'seed-audit-revoked', 'TRACE-SEED-002', CURRENT_TIMESTAMP),
('TOKEN_REFRESH_REPLAY', 'U-INSPECT-001', 'RT-REPLAY-001', 'SESSION-REPLAY-001', 'STANDARD', NULL, 'DENY', 'Seed audit for replay-blocked refresh token reuse', '127.0.0.1', 'seed-audit-replay', 'TRACE-SEED-003', CURRENT_TIMESTAMP),
('TOKEN_USER_DISABLED', 'U-B04-DISABLED-001', NULL, 'SESSION-B04-DISABLED-001', 'STANDARD', NULL, 'SUCCESS', 'Seed audit for disabled user convergence', '127.0.0.1', 'seed-audit-disabled', 'TRACE-SEED-004', CURRENT_TIMESTAMP),
('TOKEN_PERMISSION_REVOKED', 'U-B04-CONVERGED-001', NULL, 'SESSION-B04-CONVERGED-001', 'STANDARD', NULL, 'SUCCESS', 'Seed audit for permission convergence', '127.0.0.1', 'seed-audit-converged', 'TRACE-SEED-005', CURRENT_TIMESTAMP),
('BREAK_GLASS_ACCOUNT_ACTIVATED', 'U-B05-COMMAND-001', NULL, NULL, 'BREAK_GLASS', 'EA-B05-ACTIVE-001', 'SUCCESS', 'Seed audit for emergency account activation', '127.0.0.1', 'seed-break-glass-activate', 'TRACE-SEED-006', CURRENT_TIMESTAMP),
('BREAK_GLASS_LOGIN_SUCCESS', 'U-B05-COMMAND-001', NULL, 'SESSION-B05-ACTIVE-001', 'BREAK_GLASS', 'EA-B05-ACTIVE-001', 'SUCCESS', 'Seed audit for emergency login success', '127.0.0.1', 'seed-break-glass-login', 'TRACE-SEED-007', CURRENT_TIMESTAMP),
('BREAK_GLASS_ACCOUNT_REVOKED', 'U-B05-COMMAND-001', NULL, 'SESSION-B05-EXPIRED-001', 'BREAK_GLASS', 'EA-B05-EXPIRED-001', 'SUCCESS', 'Seed audit for emergency account revocation', '127.0.0.1', 'seed-break-glass-revoke', 'TRACE-SEED-008', CURRENT_TIMESTAMP);

INSERT INTO gateway_route_policy (
    policy_id, route_code, path_pattern, http_method, auth_required, risk_level, validation_profile,
    rate_limit_scope, rate_limit_capacity, rate_limit_window_seconds, audit_enabled, enabled, created_at, updated_at
) VALUES
('GWP-PUBLIC-MENU-001', 'PUBLIC_MENU_BOUNDARIES', '/api/menu-boundaries', 'GET', FALSE, 'LOW', 'NONE', 'IP', 120, 60, FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-PUBLIC-OBJECT-001', 'PUBLIC_OBJECT_DICTIONARY', '/api/object-dictionary', 'GET', FALSE, 'LOW', 'NONE', 'IP', 120, 60, FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-PUBLIC-OBJECT-PAGE-001', 'PUBLIC_OBJECT_DICTIONARY_PAGE', '/api/object-dictionary/page', 'GET', FALSE, 'LOW', 'PAGE_QUERY', 'IP', 120, 60, FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-PUBLIC-AUTHZ-MATRIX-001', 'PUBLIC_AUTHZ_MATRIX', '/api/authz/matrix', 'GET', FALSE, 'LOW', 'NONE', 'IP', 120, 60, FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-AUTH-REFRESH-001', 'AUTH_REFRESH', '/api/auth/refresh', 'POST', FALSE, 'HIGH', 'JSON_BODY', 'USER_OR_IP', 8, 60, TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-EMERGENCY-LOGIN-001', 'EMERGENCY_LOGIN', '/api/auth/emergency/login', 'POST', FALSE, 'HIGH', 'JSON_BODY', 'IP', 5, 60, TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-ADMIN-DISABLE-001', 'AUTH_ADMIN_DISABLE', '/api/auth/admin/users/*/disable', 'POST', TRUE, 'CRITICAL', 'NONE', 'USER_OR_IP', 5, 60, TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-ADMIN-PERMISSIONS-001', 'AUTH_ADMIN_PERMISSION_REVOKE', '/api/auth/admin/users/*/permissions/revoke', 'POST', TRUE, 'CRITICAL', 'NONE', 'USER_OR_IP', 5, 60, TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-EMERGENCY-ACTIVATE-001', 'EMERGENCY_ACCOUNT_ACTIVATE', '/api/auth/emergency/accounts/*/activate', 'POST', TRUE, 'CRITICAL', 'JSON_BODY', 'USER_OR_IP', 3, 60, TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-EMERGENCY-REVOKE-001', 'EMERGENCY_ACCOUNT_REVOKE', '/api/auth/emergency/accounts/*/revoke', 'POST', TRUE, 'CRITICAL', 'JSON_BODY', 'USER_OR_IP', 3, 60, TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-FUTURE-EXPORTS-001', 'FUTURE_EXPORTS', '/api/exports/**', 'POST', TRUE, 'CRITICAL', 'JSON_BODY', 'USER_OR_IP', 2, 60, TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-FUTURE-BATCH-DISPATCH-001', 'FUTURE_BATCH_DISPATCH', '/api/workorders/batch-dispatch', 'POST', TRUE, 'CRITICAL', 'JSON_BODY', 'USER_OR_IP', 2, 60, TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GWP-FUTURE-MODEL-PUBLISH-001', 'FUTURE_MODEL_PUBLISH', '/api/models/publish', 'POST', TRUE, 'CRITICAL', 'JSON_BODY', 'USER_OR_IP', 2, 60, TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO gateway_client_rule (
    rule_id, rule_type, subject_type, subject_value, reason, expires_at, enabled, created_at, updated_at
) VALUES
('GCR-ALLOW-IP-001', 'ALLOWLIST', 'IP', '10.10.10.10', 'Seed allowlist example for trusted gateway client', TIMESTAMP '2099-12-31 23:59:59', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GCR-BLOCK-IP-001', 'BLOCKLIST', 'IP', '203.0.113.77', 'Seed blocklist example for denied client IP', TIMESTAMP '2099-12-31 23:59:59', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GCR-BLOCK-USER-001', 'BLOCKLIST', 'USER', 'U-B06-BLOCKED-001', 'Seed blocklist example for denied user', TIMESTAMP '2099-12-31 23:59:59', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO gateway_risk_audit (
    route_code, path_pattern, http_method, user_id, auth_mode, decision, reason_code, risk_level, client_ip, trace_id, created_at
) VALUES
('EMERGENCY_LOGIN', '/api/auth/emergency/login', 'POST', NULL, NULL, 'ALLOW', 'ALLOW', 'HIGH', '10.10.10.10', 'TRACE-GATEWAY-SEED-001', CURRENT_TIMESTAMP),
('AUTH_ADMIN_DISABLE', '/api/auth/admin/users/*/disable', 'POST', 'U-B06-BLOCKED-001', 'STANDARD', 'DENY', 'BLOCKLIST_MATCHED', 'CRITICAL', '203.0.113.77', 'TRACE-GATEWAY-SEED-002', CURRENT_TIMESTAMP),
('AUTH_REFRESH', '/api/auth/refresh', 'POST', 'U-DISPATCH-001', 'STANDARD', 'DENY', 'RATE_LIMITED', 'HIGH', '127.0.0.1', 'TRACE-GATEWAY-SEED-003', CURRENT_TIMESTAMP);
